# Copyright 2023 StreamNative, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: alert-rules
    role: alert-rules
spec:
  groups:
  - name: olm.csv_abnormal.rules
    rules:
      - alert: CsvAbnormalFailedOver2Min
        expr: csv_abnormal{phase=~"^Failed$"}
        for: 2m
        labels:
          severity: warning
          namespace: "{{ "{{ $labels.namespace }}" }}"
        annotations:
          message: Failed to install Operator {{ printf "{{ $labels.name }}"  }} version {{ printf "{{ $labels.version }}"  }}. Reason-{{ printf "{{ $labels.reason }}" }}
      - alert: CsvAbnormalOver30Min
        expr: csv_abnormal{phase=~"(^Replacing$|^Pending$|^Deleting$|^Unknown$)"}
        for: 30m
        labels:
          severity: warning
          namespace: "{{ "{{ $labels.namespace }}" }}"
        annotations:
          message: Failed to install Operator {{ printf "{{ $labels.name }}"  }} version {{ printf "{{ $labels.version }}"  }}. Phase-{{ printf "{{ $labels.phase }}" }} Reason-{{ printf "{{ $labels.reason }}" }}
  - name: olm.installplan.rules
    rules:
    - alert: InstallPlanStepAppliedWithWarnings
      expr: sum(increase(installplan_warnings_total[5m])) > 0
      labels:
        severity: warning
      annotations:
        message: The API server returned a warning during installation or upgrade of an operator. An Event with reason "AppliedWithWarnings" has been created with complete details, including a reference to the InstallPlan step that generated the warning.
{{ end }}
