{{- if and .Values.installType (eq .Values.installType "upstream") -}}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: {{ .Values.catalog_namespace }}
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  sourceType: grpc
  image: {{ include "olm.upstreamOperatorCatalogImage" . }}
  displayName: Community Operators
  publisher: OperatorHub.io
  updateStrategy:
    registryPoll:
      interval: 60m
{{- end }}
