rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
minKubeVersion: 1.18.0
writeStatusName: '""'
imagestream: false
debug: true
installType: upstream

image:
  registry: quay.io
  repository: operator-framework
  name: olm
  tag: v0.20.0
  pullSecrets: []
  # - name: gcr-test

olm:
  replicaCount: 1
  image:
    # if you want to use a specified image, you can set ref to override the common image
    # ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
    externalPort: metrics
  # tlsSecret: olm-operator-serving-cert
  # clientCASecret: pprof-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 160Mi

catalog:
  replicaCount: 1
  commandArgs: --configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
  image:
    # ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
    externalPort: metrics
  # tlsSecret: catalog-operator-serving-cert
  # clientCASecret: pprof-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 80Mi

package:
  replicaCount: 2
  maxUnavailable: 1
  maxSurge: 1
  image:
    # if you want to use a specified image, you can set ref to override the common image
    # ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 50Mi

upstreamOperator:
  # catalog image for the upstream operator
  image:
    # ref: quay.io/operatorhubio/catalog:latest
    repository: operatorhubio
    name: catalog
    tag: latest

monitoring:
  enabled: false
  namespace: monitoring