name: PR

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}